apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: inventory-service
spec:
  accessControl:
    defaultAction: deny
    policies:
      - appId: order-manager
        defaultAction: deny
        operations:
          - name: /inventory/check
            httpVerb: ["POST"]
            action: allow
          - name: /inventory/update
            httpVerb: ["POST"]
            action: allow
          - name: /inventory/check/*
            httpVerb: ["*"]
            action: allow
          - name: /inventory/test-failure
            httpVerb: ["GET"]
            action: allow
